services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/xplorer
      DATABASE_URL_TEST: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-test:5432/xplorer_test
    ports:
      - "8000:8000"
    networks:
      - devnet

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: xplorer
    ports:
      - "5432:5432"
    networks:
      - devnet

  db-test:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: xplorer_test
    ports:
      - "5433:5432"
    networks:
      - devnet

volumes:
  postgres_data: {}  # You can remove this completely if using anonymous volume

networks:
  devnet:
